/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useContext, useEffect, useRef, useState } from "react";
import {
  useGLTF,
  useAnimations,
  useTexture,
  Gltf,
  Text,
} from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeEvent, useFrame, useThree } from "@react-three/fiber";
import { ItemContext } from "./ItemContext";

type GLTFResult = GLTF & {
  nodes: {
    Plane002: THREE.Mesh;
    Plane002_1: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane005_1: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane006_1: THREE.Mesh;
  };
};

type ActionName = "Scene";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

type ThickMagazineProps = {
  pagePath: string;
  pageCount: number;
  cyclePage: (direction: number) => void;
  currentPage: number;
  isHeld: boolean;
};

const FRAMES_PER_SEC = 24;
const PAGE_FLIP_FRAMES = 30;

export default function ThickMagazine(
  props: JSX.IntrinsicElements["group"] & ThickMagazineProps,
) {
  const group = useRef<THREE.Group>(null);
  const actionRef = useRef<THREE.AnimationAction>();
  const keyframeRef = useRef(0);
  let { nodes, _materials, animations } = useGLTF(
    "/ThickMagazine.glb",
  ) as GLTFResult;
  const { ref, actions } = useAnimations(animations);
  const defaultMaterial = new THREE.MeshStandardMaterial({ color: "white" });
  const pageMaterials = new Array<THREE.MeshStandardMaterial>(5).fill(
    defaultMaterial,
  );
  const { setItem } = useContext(ItemContext);

  // HACK: The way the blender animation is setup, it finishes
  // at a hardcoded z value, so I can't add more pages without
  // manually editing the animation... five should be enough for all cases,
  // but it is a sad limitation of the situation.
  for (let i = 0; i < props.pageCount; i++) {
    const pageTexture = useTexture(`${props.pagePath}/Page ${i + 1}.png`);
    pageTexture.center = new THREE.Vector2(0.5, 0.5);
    pageTexture.rotation = Math.PI;
    // gotta flip every other page
    pageTexture.repeat.x = i % 2 === 0 ? -1 : 1;
    pageMaterials[i] = new THREE.MeshStandardMaterial({ map: pageTexture });
  }

  const calcFrame = (pg: number) => {
    return (PAGE_FLIP_FRAMES * pg) / FRAMES_PER_SEC;
  };

  useEffect(() => {
    actions.Test?.setLoop(THREE.LoopOnce, 1);
    actions.Test?.play();

    actionRef!.current = actions.Test ?? undefined;
    actionRef!.current.timeScale = 0;
  }, [actions.Test]);

  useEffect(() => {
    keyframeRef.current = calcFrame(props.currentPage);
  }, [props.currentPage, calcFrame]);

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === "q") {
      props.cyclePage(-1);
    } else if (e.key === "e") {
      props.cyclePage(1);
    } else if (e.key === "Escape") {
      setItem("");
    }
  };

  useEffect(() => {
    if (props.isHeld) {
      document.addEventListener("keydown", handleKeyDown);

      return () => {
        document.removeEventListener("keydown", handleKeyDown);
      };
    }
  }, [props.isHeld, handleKeyDown]);

  useFrame(() => {
    if (actionRef.current) {
      const diff = actionRef.current.time - keyframeRef.current;
      if (Math.abs(diff) < 0.1) {
        actionRef.current.timeScale = 0;
      } else if (diff > 0) {
        actionRef.current.timeScale = -2;
      } else {
        actionRef.current.timeScale = 2;
      }
    }
  });

  // HACK: I have to clone geometry because otherwise the
  // animations are shared between books
  for (const name in nodes) {
    nodes[name] = nodes[name].clone();
  }
  return (
    <group {...props} dispose={null} ref={ref}>
      <group name="Scene">
        <group name="Sheet1" position={[0, 0.02, 0]}>
          <mesh
            name="Plane002"
            geometry={nodes.Plane002.geometry.clone()}
            material={pageMaterials[0]}
            morphTargetDictionary={nodes.Plane002.morphTargetDictionary}
            morphTargetInfluences={nodes.Plane002.morphTargetInfluences}
          />
          <mesh
            name="Plane002_1"
            geometry={nodes.Plane002_1.geometry.clone()}
            material={pageMaterials[1]}
            morphTargetDictionary={nodes.Plane002_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Plane002_1.morphTargetInfluences}
          />
        </group>
        <group name="Sheet2" position={[0, 0.01, 0]}>
          <mesh
            name="Plane005"
            geometry={nodes.Plane005.geometry.clone()}
            material={pageMaterials[2]}
            morphTargetDictionary={nodes.Plane005.morphTargetDictionary}
            morphTargetInfluences={nodes.Plane005.morphTargetInfluences}
          />
          <mesh
            name="Plane005_1"
            geometry={nodes.Plane005_1.geometry.clone()}
            material={pageMaterials[3]}
            morphTargetDictionary={nodes.Plane005_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Plane005_1.morphTargetInfluences}
          />
        </group>
        <group name="Sheet3">
          <mesh
            name="Plane006"
            geometry={nodes.Plane006.geometry}
            material={pageMaterials[4]}
            morphTargetDictionary={nodes.Plane006.morphTargetDictionary}
            morphTargetInfluences={nodes.Plane006.morphTargetInfluences}
          />
          <mesh
            name="Plane006_1"
            geometry={nodes.Plane006_1.geometry}
            material={pageMaterials[5]}
            morphTargetDictionary={nodes.Plane006_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Plane006_1.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  );
}
